  const travelData = [
    {
        id: '1',
        name: 'Ahmed Sajjad',
        rating: 4,
        reviewCount: 25,
        departTime: '4:00 PM',
        arriveTime: '8:00 PM',
        fromCode: 'DXB',
        fromCity: 'Dubai',
        fromFlag: '🇦🇪',
        toCode: 'LHR',
        toCity: 'Lahore',
        toFlag: '🇵🇰',
        date: '24 July 2025',
        image: 'https://images.unsplash.com/photo-1506794778202-dfa467e9149c?w=200',
    },
    {
        id: '2',
        name: 'Ahmed Sajjad',
        rating: 4,
        reviewCount: 25,
        departTime: '4:00 PM',
        arriveTime: '8:00 PM',
        fromCode: 'LHR',
        fromCity: 'Lahore',
        fromFlag: '🇵🇰',
        toCode: 'DXB',
        toCity: 'Dubai',
        toFlag: '🇦🇪',
        date: '24 July 2025',
        image: 'https://images.unsplash.com/photo-1531427186252-ad0672051e8e?w=200',
    },
    {
        id: '3',
        name: 'Ahmed Sajjad',
        rating: 4,
        reviewCount: 25,
        departTime: '4:00 PM',
        arriveTime: '8:00 PM',
        fromCode: 'DXB',
        fromCity: 'Dubai',
        fromFlag: '🇦🇪',
        toCode: 'LHR',
        toCity: 'Lahore',
        toFlag: '🇵🇰',
        date: '24 July 2025',
        image: 'https://images.unsplash.com/photo-1547425260-76bc0fa69598?w=200',
    },
];

export default travelData;